"use client";
import { useEffect,useRef,useState } from "react";
import { ArrowLeft,ArrowDown,ArrowUp,Bold,Check,ChevronLeft,ChevronRight,Download,FilePlus2,FileText,Highlighter,Italic, List, LoaderCircle, MousePointer2, PenLine, Plus, Redo2, RotateCw, Scissors, Trash2, Type, Underline,Undo2, X,ZoomIn,ZoomOut } from "lucide-react";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from "@/components/ui/alert-dialog";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import { toast } from "sonner";
import { download,exportPdf,extractPdfText,imagePdf,importWord,loadPdf,mergePdf,safeHtml,stem,wordDocx,wordPdf,type Mark,type PageItem } from "@/lib/documents";

type Snapshot={pages:PageItem[];marks:Mark[]};
type Tool="select"|"text"|"draw"|"highlight"|"signature";
function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="editor-select"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>}
function IconButton({label,children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{label:string}){return <button {...props} className={`icon-button ${props.className||""}`} aria-label={label} title={label}>{children}</button>}
export default function Workspace({files,intent,onClose,onDirty}:{files:File[];intent:string;onClose:()=>void;onOpen:(s:string)=>void;onDirty?:(dirty:boolean)=>void}){
 const [kind,setKind]=useState<"pdf"|"word">("pdf"),[name,setName]=useState(stem(files[0].name)),[busy,setBusy]=useState("Belgen açılıyor…"),[error,setError]=useState(""),[dirty,setDirty]=useState(false),[exit,setExit]=useState(false);
 const [bytes,setBytes]=useState<Uint8Array|null>(null),[pdf,setPdf]=useState<any>(null),[state,setState]=useState<Snapshot>({pages:[],marks:[]}),[history,setHistory]=useState<Snapshot[]>([]),[future,setFuture]=useState<Snapshot[]>([]);
 const [active,setActive]=useState(0),[tool,setTool]=useState<Tool>("select"),[selected,setSelected]=useState<string|null>(null),[zoom,setZoom]=useState(1),[color,setColor]=useState("#30294d"),[text,setText]=useState("Yeni metin"),[size,setSize]=useState(16),[sig,setSig]=useState<string|null>(null),[signOpen,setSignOpen]=useState(false),[exportOpen,setExportOpen]=useState(intent==="convert"),[format,setFormat]=useState("pdf"),[range,setRange]=useState(""),[rangeError,setRangeError]=useState("");
 const [dimensions,setDimensions]=useState({width:595,height:842,baseWidth:595,baseHeight:842}),[rendering,setRendering]=useState(false),[count,setCount]=useState(0),[draft,setDraft]=useState<Mark|null>(null);
 const canvas=useRef<HTMLCanvasElement>(null),surface=useRef<HTMLDivElement>(null),editor=useRef<HTMLDivElement>(null),mergeInput=useRef<HTMLInputElement>(null),htmlRef=useRef("<p><br></p>"),selection=useRef<Range|null>(null),gesture=useRef<any>(null),renderTask=useRef<any>(null);
 const current=state.pages[active],currentMark=state.marks.find(m=>m.id===selected);
 const hydrated=useRef(false),pdfRef=useRef<any>(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 useEffect(()=>{onDirty?.(dirty);return()=>onDirty?.(false)},[dirty,onDirty]);
 useEffect(()=>{pdfRef.current=pdf},[pdf]);
 useEffect(()=>()=>{void pdfRef.current?.loadingTask.destroy().catch(()=>{})},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();const register=(spec:any)=>{try{Promise.resolve(ctx.registerTool(spec,{signal:lifecycle.signal})).catch(()=>{})}catch{}};register({name:"read_document_status",description:"Read the open document type, page count, current page, and unsaved-change status. Does not expose document contents.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({type:kind,pages:state.pages.length,currentPage:active+1,annotations:state.marks.length,unsaved:dirty,busy:!!busy})});register({name:"add_pdf_text",description:"Add a visible text annotation to the currently selected PDF page. Does not download the file.",inputSchema:{type:"object",properties:{text:{type:"string",minLength:1,maxLength:300},x:{type:"number",minimum:0},y:{type:"number",minimum:0}},required:["text","x","y"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(kind!=="pdf"||!current||busy)throw Error("No PDF is ready.");if(typeof input?.text!=="string"||!input.text.trim()||input.text.length>300||!Number.isFinite(input.x)||!Number.isFinite(input.y)||input.x<0||input.y<0||input.x>dimensions.baseWidth||input.y>dimensions.baseHeight)throw Error("Invalid text or page position.");const mark={...newMark("text",input.x,input.y),text:input.text};addMark(mark);await new Promise(requestAnimationFrame);return{added:true,page:active+1,id:mark.id}}});return()=>lifecycle.abort()},[kind,state,active,dirty,busy,dimensions]);
 function change(next:Snapshot){setHistory(h=>[...h.slice(-39),state]);setFuture([]);setState(next);setDirty(true)}
 function undo(){if(!history.length)return;setFuture(f=>[state,...f]);const next=history[history.length-1];setState(next);setHistory(h=>h.slice(0,-1));setActive(a=>Math.min(a,next.pages.length-1));setSelected(null);setDirty(true)}
 function redo(){if(!future.length)return;setHistory(h=>[...h,state]);setState(future[0]);setActive(a=>Math.min(a,future[0].pages.length-1));setFuture(f=>f.slice(1));setSelected(null);setDirty(true)}
 async function installPdf(data:Uint8Array){const next=await loadPdf(data);if(!alive.current){await next.loadingTask.destroy();return}setPdf((old:any)=>{void old?.loadingTask.destroy().catch(()=>{});return next});setBytes(data);setState({pages:Array.from({length:next.numPages},(_,index)=>({index,rotation:0})),marks:[]});setHistory([]);setFuture([]);setActive(0);setSelected(null);setKind("pdf")}
 useEffect(()=>{let stopped=false;async function start(){try{const first=files[0];if(/\.(docx|txt)$/i.test(first.name)){const html=await importWord(first);if(stopped)return;htmlRef.current=html;setKind("word");setCount(html.replace(/<[^>]+>/g," ").trim().split(/\s+/).filter(Boolean).length);setFormat(intent==="convert"?"pdf":"docx")}else{const data=/\.(png|jpe?g)$/i.test(first.name)?await imagePdf(files):files.length>1?await mergePdf(files):new Uint8Array(await first.arrayBuffer());if(stopped)return;await installPdf(data);if(intent==="sign")setSignOpen(true)}}catch(e){if(!stopped)setError(/encrypt|password/i.test(String(e))?"Bu PDF şifreli. Önce parolasını kaldırarak yeniden aç.":"Bu dosya açılamadı. Dosyanın geçerli ve bozulmamış bir PDF veya DOCX olduğundan emin ol.")}finally{if(!stopped)setBusy("")}}void start();return()=>{stopped=true}},[files,intent]);
 useEffect(()=>{if(kind==="word"&&!busy&&editor.current&&!hydrated.current){editor.current.innerHTML=htmlRef.current;hydrated.current=true}},[kind,busy]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler)},[dirty]);
 useEffect(()=>{return()=>{renderTask.current?.cancel()}},[]);
 useEffect(()=>{if(!pdf||!current||!canvas.current||kind!=="pdf")return;let cancelled=false;renderTask.current?.cancel();setRendering(true);void(async()=>{try{const page=await pdf.getPage(current.index+1);if(cancelled)return;const base=page.getViewport({scale:1});const view=page.getViewport({scale:1,rotation:(page.rotate+current.rotation)%360});setDimensions({width:view.width,height:view.height,baseWidth:base.width,baseHeight:base.height});const c=canvas.current;if(!c||cancelled)return;const viewport=page.getViewport({scale:Math.min(window.devicePixelRatio||1,2)*zoom,rotation:(page.rotate+current.rotation)%360});c.width=viewport.width;c.height=viewport.height;const task=page.render({canvasContext:c.getContext("2d")!,canvas:c,viewport});renderTask.current=task;await task.promise;if(!cancelled)setRendering(false)}catch(e){if(!cancelled&&!/RenderingCancelled/.test(String(e))){toast.error("Sayfa görüntülenemedi.");setRendering(false)}}})();return()=>{cancelled=true;renderTask.current?.cancel()}},[pdf,current?.index,current?.rotation,zoom,kind,busy]);
 function addMark(mark:Mark){change({...state,marks:[...state.marks,mark]});setSelected(mark.id)}
 function newMark(kind:Mark["kind"],x:number,y:number):Mark{return{id:crypto.randomUUID(),page:current.index,kind,x,y,w:kind==="signature"?180:150,h:kind==="signature"?67.5:24,color:kind==="highlight"?"#ffdb3d":color,size:kind==="draw"?2:size,text,image:sig||undefined,points:[]}}
 function basePoint(e:React.PointerEvent){const box=surface.current!.getBoundingClientRect();const x=(e.clientX-box.left)/box.width*dimensions.width,y=(e.clientY-box.top)/box.height*dimensions.height;const r=current.rotation;let p=r===90?{x:y,y:dimensions.baseHeight-x}:r===180?{x:dimensions.baseWidth-x,y:dimensions.baseHeight-y}:r===270?{x:dimensions.baseWidth-y,y:x}:{x,y};return{x:Math.max(0,Math.min(dimensions.baseWidth,p.x)),y:Math.max(0,Math.min(dimensions.baseHeight,p.y))}}
 function pointerDown(e:React.PointerEvent){if(busy||rendering||!current)return;if(tool==="select")return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);const p=basePoint(e);if(tool==="text"){addMark(newMark("text",p.x,p.y));setTool("select")}else if(tool==="signature"){if(!sig){setSignOpen(true);return}addMark(newMark("signature",p.x,p.y));setTool("select")}else{const m=newMark(tool,p.x,p.y);m.points=[p];m.w=0;m.h=0;gesture.current={mark:m,start:p};setDraft(m)}}
 function pointerMove(e:React.PointerEvent){const g=gesture.current;if(!g)return;const p=basePoint(e);if(g.move){const dx=p.x-g.start.x,dy=p.y-g.start.y;setDraft({...g.mark,x:Math.max(0,g.mark.x+dx),y:Math.max(0,g.mark.y+dy),points:g.mark.points?.map((pt:any)=>({x:pt.x+dx,y:pt.y+dy}))});return}if(g.mark.kind==="draw"){g.mark={...g.mark,points:[...g.mark.points,p]}}else g.mark={...g.mark,x:Math.min(p.x,g.start.x),y:Math.min(p.y,g.start.y),w:Math.abs(p.x-g.start.x),h:Math.abs(p.y-g.start.y)};setDraft(g.mark)}
 function pointerUp(){const g=gesture.current;if(!g)return;if(draft){if(g.move)change({...state,marks:state.marks.map(m=>m.id===draft.id?draft:m)});else if(draft.kind==="draw"?(draft.points?.length||0)>1:draft.w>2&&draft.h>2)addMark(draft)}setDraft(null);gesture.current=null}
 function updateMark(values:Partial<Mark>){if(currentMark)change({...state,marks:state.marks.map(m=>m.id===selected?{...m,...values,points:m.kind==="draw"?m.points?.map(p=>({x:p.x+(values.x===undefined?0:values.x-m.x),y:p.y+(values.y===undefined?0:values.y-m.y)})):m.points}:m)})}
 function rotate(){change({...state,pages:state.pages.map((p,i)=>i===active?{...p,rotation:(p.rotation+90)%360}:p)})}
 function removePage(){if(state.pages.length===1){toast.error("Belgede en az bir sayfa kalmalı.");return}change({...state,pages:state.pages.filter((_,i)=>i!==active)});setActive(Math.max(0,active-1));setSelected(null)}
 function movePage(direction:number){const to=active+direction;if(to<0||to>=state.pages.length)return;const pages=[...state.pages];[pages[active],pages[to]]=[pages[to],pages[active]];change({...state,pages});setActive(to)}
 async function append(files:File[]){if(!bytes||!files.length)return;if(files.some(f=>! /\.pdf$/i.test(f.name)||f.size>50*1024*1024)){toast.error("En fazla 50 MB olan PDF dosyaları seç.");return}setBusy("PDF’ler birleştiriliyor…");try{const data=await mergePdf([new File([bytes as BlobPart],"mevcut.pdf"),...files]);const next=await loadPdf(data);const added=Array.from({length:next.numPages-pdf.numPages},(_,i)=>({index:pdf.numPages+i,rotation:0}));renderTask.current?.cancel();setPdf(next);setBytes(data);change({...state,pages:[...state.pages,...added]});void pdf.loadingTask.destroy().catch(()=>{});toast.success("Sayfalar belgenin sonuna eklendi.")}catch{toast.error("PDF birleştirilemedi. Dosya şifreli veya bozuk olabilir.")}finally{setBusy("")}}
 function selectedPages(){if(!range.trim())return state.pages;const indices:number[]=[];for(const part of range.split(",")){const match=part.trim().match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!match)throw Error("Sayfaları 1, 3-5 biçiminde yaz.");const from=Number(match[1]),to=Number(match[2]||match[1]);if(from<1||to>state.pages.length||from>to)throw Error(`1 ile ${state.pages.length} arasında sayfalar seç.`);for(let n=from;n<=to;n++)if(!indices.includes(n-1))indices.push(n-1)}return indices.map(i=>state.pages[i])}
 async function save(){setRangeError("");setBusy("Dosyan hazırlanıyor…");try{if(kind==="word"){const html=editor.current?.innerHTML||htmlRef.current;const result=format==="pdf"?await wordPdf(html):format==="docx"?await wordDocx(html):new Blob([editor.current?.innerText||""],{type:"text/plain;charset=utf-8"});download(result,`${name||"belge"}.${format}`)}else if(bytes){let pages:PageItem[];try{pages=selectedPages()}catch(e){setRangeError((e as Error).message);return}if(format==="pdf")download(await exportPdf(bytes,pages,state.marks),`${name||"belge"}.pdf`);else{const edited=await exportPdf(bytes,pages,state.marks);const text=await extractPdfText(edited);if(!text.trim())throw Error("Bu PDF’de seçilebilir metin bulunamadı. Taranmış belgeler için OCR gerekir.");if(format==="txt")download(new Blob([text],{type:"text/plain;charset=utf-8"}),`${name||"belge"}.txt`);else{const div=document.createElement("div");div.textContent=text;download(await wordDocx(div.innerHTML.split("\n").map(s=>`<p>${s}</p>`).join("")),`${name||"belge"}.docx`)}}}setExportOpen(false);if((kind==="word"&&format==="docx")||(kind==="pdf"&&format==="pdf"&&!range.trim()))setDirty(false);toast.success("Dosyan hazır, indirme başlatıldı.")}catch(e){toast.error((e as Error).message||"Dosya oluşturulamadı.")}finally{setBusy("")}}
 function rememberSelection(){const s=window.getSelection();if(s?.rangeCount&&editor.current?.contains(s.anchorNode))selection.current=s.getRangeAt(0).cloneRange()}
 function command(cmd:string,value?:string){editor.current?.focus();if(selection.current){const s=window.getSelection();s?.removeAllRanges();s?.addRange(selection.current)}document.execCommand(cmd,false,value);if(editor.current){htmlRef.current=editor.current.innerHTML;setCount(editor.current.innerText.trim().split(/\s+/).filter(Boolean).length)}setDirty(true);rememberSelection()}
 const transform=current?.rotation===90?`translate(${dimensions.baseHeight} 0) rotate(90)`:current?.rotation===180?`translate(${dimensions.baseWidth} ${dimensions.baseHeight}) rotate(180)`:current?.rotation===270?`translate(0 ${dimensions.baseWidth}) rotate(270)`:undefined;
 const visibleMarks=[...state.marks.filter(m=>m.page===current?.index&&m.id!==draft?.id),...(draft?[draft]:[])];
 function drawMark(m:Mark){return <g key={m.id} className={tool==="select"?"selectable-mark":""} onPointerDown={e=>{if(tool!=="select")return;e.stopPropagation();e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);setSelected(m.id);gesture.current={move:true,mark:m,start:basePoint(e)};setDraft(m)}}>{m.kind==="text"?<text x={m.x} y={m.y+m.size} fontSize={m.size} fontFamily="Forma Roboto, sans-serif" fill={m.color}>{m.text}</text>:m.kind==="highlight"?<rect x={m.x} y={m.y} width={m.w} height={m.h} fill={m.color} opacity=".3"/>:m.kind==="signature"?<image href={m.image} x={m.x} y={m.y} width={m.w} height={m.h}/>:<polyline points={m.points?.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke={m.color} strokeWidth={m.size} strokeLinecap="round" strokeLinejoin="round"/>}{m.id===selected&&m.kind!=="draw"&&<rect x={m.x-3} y={m.y-3} width={m.kind==="text"?Math.max(25,(m.text?.length||1)*m.size*.56):m.w+6} height={m.kind==="text"?m.size*1.4:m.h+6} fill="none" stroke="#8064d8" strokeWidth="1" strokeDasharray="4 3" pointerEvents="none"/>}</g>}
 if(error)return <div className="editor-error"><FileText size={38}/><h2>Dosyayı açamadık</h2><p>{error}</p><button className="primary" onClick={onClose}>Araçlara dön</button></div>;
 return <div className="editor-shell">
 <div className="editor-heading"><IconButton label="Araçlara dön" onClick={()=>dirty?setExit(true):onClose()}><ArrowLeft size={19}/></IconButton><span className={`tool-icon ${kind==="pdf"?"violet":"blue"}`}><FileText size={22}/></span><div className="editor-title"><input aria-label="Belge adı" value={name} onChange={e=>setName(e.target.value)}/><span>{kind==="pdf"?`${state.pages.length} sayfa · PDF`:`${count} kelime · Word`}<i/> {dirty?"İndirilmemiş değişiklikler":"Cihazında açık"}</span></div><button className="primary" disabled={!!busy} onClick={()=>setExportOpen(true)}><Download size={17}/><span>Dışa aktar</span></button></div>
 {kind==="pdf"?<><fieldset disabled={!!busy} className="editor-toolbar"><div className="tool-buttons">{[{id:"select",label:"Seç",icon:MousePointer2},{id:"text",label:"Metin",icon:Type},{id:"highlight",label:"Vurgula",icon:Highlighter},{id:"draw",label:"Çiz",icon:PenLine}].map(t=><button key={t.id} className={tool===t.id?"active":""} aria-pressed={tool===t.id} onClick={()=>{setTool(t.id as Tool);setSelected(null)}}><t.icon size={17}/>{t.label}</button>)}<button className={tool==="signature"?"active":""} onClick={()=>setSignOpen(true)}><PenLine size={17}/> İmza</button></div><div className="toolbar-divider"/><IconButton label="Geri al" onClick={undo} disabled={!history.length}><Undo2 size={17}/></IconButton><IconButton label="Yinele" onClick={redo} disabled={!future.length}><Redo2 size={17}/></IconButton><span className="toolbar-spacer"/><IconButton label="Uzaklaştır" onClick={()=>setZoom(z=>Math.max(.4,z-.15))}><ZoomOut size={17}/></IconButton><span className="zoom-label">%{Math.round(zoom*100)}</span><IconButton label="Yakınlaştır" onClick={()=>setZoom(z=>Math.min(2,z+.15))}><ZoomIn size={17}/></IconButton></fieldset>
 <div className="pdf-workarea"><aside className="page-panel"><div className="panel-heading"><strong>Sayfalar</strong><span>{state.pages.length}</span></div><div className="page-list">{state.pages.map((p,i)=><button key={p.index} className={`page-thumb ${active===i?"active":""}`} aria-label={`Sayfa ${i+1}`} aria-current={active===i?"page":undefined} onClick={()=>{setActive(i);setSelected(null)}}><FileText size={30}/><span>{i+1}</span>{p.rotation!==0&&<small>{p.rotation}°</small>}</button>)}</div><button className="add-pages" disabled={!!busy} onClick={()=>mergeInput.current?.click()}><Plus size={16}/> PDF ekle</button><p>Eklenen sayfalar sona gelir.</p></aside>
 <div className="page-viewer"><div className="page-hint">{tool==="text"?"Metin eklemek istediğin yere tıkla.":tool==="highlight"?"Vurgulamak istediğin alanı sürükleyerek seç.":tool==="draw"?"Sayfanın üzerinde çizim yap.":tool==="signature"?"İmzayı yerleştirmek istediğin yere tıkla.":"Eklediğin öğeyi seç; sürükle veya konumunu sağdan ayarla."}</div><div className="page-scroll"><div className={`pdf-surface tool-${tool}`} ref={surface} style={{width:dimensions.width*zoom,height:dimensions.height*zoom}} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={()=>{gesture.current=null;setDraft(null)}}><canvas ref={canvas} aria-label={`PDF sayfa ${active+1}`} style={{width:"100%",height:"100%"}}/><svg className="annotation-layer" viewBox={`0 0 ${dimensions.width} ${dimensions.height}`}><g transform={transform}>{visibleMarks.map(drawMark)}</g></svg>{rendering&&<div className="rendering-label"><LoaderCircle className="spin" size={15}/> Sayfa yükleniyor</div>}</div></div><div className="page-bottom"><IconButton label="Önceki sayfa" disabled={active===0} onClick={()=>setActive(a=>a-1)}><ChevronLeft size={17}/></IconButton><span>{active+1} / {state.pages.length}</span><IconButton label="Sonraki sayfa" disabled={active>=state.pages.length-1} onClick={()=>setActive(a=>a+1)}><ChevronRight size={17}/></IconButton></div></div>
 <aside className="properties-panel"><strong>{currentMark?"Seçili öğe":"Araç ayarları"}</strong>{(tool==="text"||currentMark?.kind==="text")&&<><label>Metin<input value={currentMark?.text??text} onChange={e=>currentMark?updateMark({text:e.target.value}):setText(e.target.value)}/></label><label>Yazı boyutu<input type="number" min="8" max="96" value={currentMark?.size??size} onChange={e=>{const v=Math.max(8,Math.min(96,Number(e.target.value)||16));currentMark?updateMark({size:v}):setSize(v)}}/></label></>}
 <label>Renk<input type="color" value={currentMark?.color??color} onChange={e=>currentMark?updateMark({color:e.target.value}):setColor(e.target.value)}/></label>
 {currentMark&&<><div className="position-fields"><label>X<input type="number" value={Math.round(currentMark.x)} onChange={e=>updateMark({x:Math.max(0,Math.min(dimensions.baseWidth,Number(e.target.value)))})}/></label><label>Y<input type="number" value={Math.round(currentMark.y)} onChange={e=>updateMark({y:Math.max(0,Math.min(dimensions.baseHeight,Number(e.target.value)))})}/></label></div>{currentMark.kind==="signature"&&<label>Genişlik<input type="number" min="30" max="500" value={currentMark.w} onChange={e=>{const w=Math.max(30,Math.min(500,Number(e.target.value)));updateMark({w,h:w*currentMark.h/currentMark.w})}}/></label>}<button className="delete-mark" onClick={()=>{change({...state,marks:state.marks.filter(m=>m.id!==selected)});setSelected(null)}}><Trash2 size={15}/> Öğeyi sil</button></>}
 {!currentMark&&(tool==="text"||tool==="signature")&&<button className="secondary" onClick={()=>{if(tool==="signature"&&!sig){setSignOpen(true);return}addMark(newMark(tool as "text"|"signature",50,80));setTool("select")}}>Sayfaya ekle</button>}
 <div className="properties-separator"/><strong>Sayfa işlemleri</strong><div className="page-actions"><button onClick={rotate} disabled={!current||!!busy}><RotateCw size={16}/> 90° döndür</button><button onClick={()=>movePage(-1)} disabled={!current||active===0||!!busy}><ArrowUp size={16}/> Öne taşı</button><button onClick={()=>movePage(1)} disabled={!current||active===state.pages.length-1||!!busy}><ArrowDown size={16}/> Arkaya taşı</button><button onClick={()=>{setRange(String(active+1));setFormat("pdf");setExportOpen(true)}} disabled={!current||!!busy}><Scissors size={16}/> Bu sayfayı ayır</button><button onClick={removePage} disabled={state.pages.length<2||!!busy}><Trash2 size={16}/> Sayfayı sil</button></div><div className="editor-note">Metin ve çizimler PDF’nin üzerine eklenir. Mevcut metni değiştirmek için Word’e dönüştürebilirsin.</div></aside></div></>:<><div className="editor-toolbar word-toolbar"><Choice label="Paragraf biçimi" value="p" onChange={v=>command("formatBlock",v)} items={[{value:"p",label:"Normal metin"},{value:"h1",label:"Başlık 1"},{value:"h2",label:"Başlık 2"}]}/><div className="toolbar-divider"/>{[{label:"Kalın",cmd:"bold",icon:Bold},{label:"İtalik",cmd:"italic",icon:Italic},{label:"Altı çizili",cmd:"underline",icon:Underline},{label:"Madde işaretleri",cmd:"insertUnorderedList",icon:List},{label:"Geri al",cmd:"undo",icon:Undo2},{label:"Yinele",cmd:"redo",icon:Redo2}].map(b=><IconButton key={b.cmd} label={b.label} onMouseDown={e=>e.preventDefault()} onClick={()=>command(b.cmd)}><b.icon size={17}/></IconButton>)}</div><div className="word-workarea"><div className="word-info">Temel metin, başlık, liste ve tablolar düzenlenebilir. Karmaşık Word yerleşimleri sadeleşebilir.</div><div ref={editor} className="word-paper" contentEditable={!busy} suppressContentEditableWarning role="textbox" aria-label="Belge metni" aria-multiline="true" spellCheck lang="tr" onMouseUp={rememberSelection} onKeyUp={rememberSelection} onInput={()=>{htmlRef.current=editor.current?.innerHTML||"";setCount((editor.current?.innerText||"").trim().split(/\s+/).filter(Boolean).length);setDirty(true);rememberSelection()}} onPaste={e=>{e.preventDefault();const html=e.clipboardData.getData("text/html");if(html)command("insertHTML",safeHtml(html));else command("insertText",e.clipboardData.getData("text/plain"))}}/></div></>}
 {busy&&<div className="busy-overlay" role="status"><LoaderCircle className="spin" size={30}/><strong>{busy}</strong></div>}
 <input type="file" className="sr-only" tabIndex={-1} ref={mergeInput} accept=".pdf" multiple aria-label="Birleştirilecek PDF dosyaları" onChange={e=>{void append(Array.from(e.target.files||[]));e.target.value=""}}/>
 <SignatureDialog open={signOpen} onOpenChange={setSignOpen} onSave={data=>{setSig(data);setSignOpen(false);setTool("signature");setSelected(null);toast("İmzayı yerleştirmek için sayfaya tıkla.")}}/>
 <Dialog open={exportOpen&&!busy} onOpenChange={setExportOpen}><DialogContent className="forma-dialog export-dialog"><DialogTitle>Belgeni dışa aktar</DialogTitle><DialogDescription>Düzenlediğin dosyanın bir kopyasını cihazına indir.</DialogDescription><label>Dosya adı<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Dosya türü</label><Choice label="Dosya türü" value={format} onChange={setFormat} items={[{value:"pdf",label:"PDF belgesi (.pdf)"},{value:"docx",label:"Word belgesi (.docx)"},{value:"txt",label:"Düz metin (.txt)"}]}/>{kind==="pdf"&&<label>Sayfalar<input placeholder="Tüm sayfalar · Örnek: 1, 3-5" value={range} onChange={e=>{setRange(e.target.value);setRangeError("")}}/><small>Görünen sayfa sırasına göre. Boş bırakırsan tüm sayfalar alınır.</small>{rangeError&&<span role="alert" className="field-error">{rangeError}</span>}</label>}{kind==="pdf"&&format!=="pdf"&&<p className="conversion-note">Bu dönüşüm PDF’deki seçilebilir metni alır. Sayfa tasarımı, resimler ve imzalar Word/TXT dosyasına taşınmaz. Taranmış sayfalarda OCR gerekir.</p>}{kind==="word"&&format!=="txt"&&<p className="conversion-note">Temel biçimlendirme korunur. Özgün Word sayfa düzeni farklı görünebilir.</p>}<button className="primary" onClick={()=>void save()}><Download size={17}/> Dosyayı indir</button></DialogContent></Dialog>
 <AlertDialog open={exit} onOpenChange={setExit}><AlertDialogContent><AlertDialogTitle>İndirmeden çıkılsın mı?</AlertDialogTitle><AlertDialogDescription>Bu belgedeki değişiklikler henüz indirilmedi. Çıkarsan tarayıcıdaki değişiklikler kaybolur.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Düzenlemeye dön</AlertDialogCancel><AlertDialogAction onClick={onClose}>İndirmeden çık</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}

function SignatureDialog({open,onOpenChange,onSave}:{open:boolean;onOpenChange:(v:boolean)=>void;onSave:(data:string)=>void}){
 const [mode,setMode]=useState("draw"),[name,setName]=useState(""),[drawn,setDrawn]=useState(false);const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false);
 useEffect(()=>{if(open){setDrawn(false);setName("");setMode("draw")}},[open]);
 function draw(e:React.PointerEvent<HTMLCanvasElement>){const c=e.currentTarget,ctx=c.getContext("2d")!,box=c.getBoundingClientRect();const x=(e.clientX-box.left)/box.width*c.width,y=(e.clientY-box.top)/box.height*c.height;if(e.type==="pointerdown"){drawing.current=true;c.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(x,y)}else if(drawing.current){ctx.lineWidth=3;ctx.strokeStyle="#282c48";ctx.lineCap="round";ctx.lineJoin="round";ctx.lineTo(x,y);ctx.stroke();setDrawn(true)}}
 function save(){if(mode==="draw"){if(drawn&&canvas.current)onSave(canvas.current.toDataURL("image/png"))}else if(name.trim()){const c=document.createElement("canvas");c.width=640;c.height=240;const ctx=c.getContext("2d")!;ctx.fillStyle="#282c48";ctx.font="italic 64px Georgia, serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(name.trim(),320,120,600);onSave(c.toDataURL("image/png"))}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="forma-dialog signature-dialog"><DialogTitle>İmzanı oluştur</DialogTitle><DialogDescription>İmzanı çiz veya adını yazarak oluştur. Sonra PDF’de yerine koy.</DialogDescription><Tabs value={mode} onValueChange={setMode}><TabsList><TabsTrigger value="draw">İmza çiz</TabsTrigger><TabsTrigger value="type">Yazarak oluştur</TabsTrigger></TabsList><TabsContent value="draw" forceMount hidden={mode!=="draw"}><canvas ref={canvas} width={640} height={240} className="signature-canvas" aria-label="İmzanı çiz" onPointerDown={draw} onPointerMove={draw} onPointerUp={()=>drawing.current=false} onPointerCancel={()=>drawing.current=false}/><button className="clear-signature" onClick={()=>{canvas.current?.getContext("2d")?.clearRect(0,0,640,240);setDrawn(false)}}><Trash2 size={14}/> Temizle</button></TabsContent><TabsContent value="type"><label>Adın ve soyadın<input autoFocus value={name} onChange={e=>setName(e.target.value)} maxLength={60} placeholder="Ad Soyad"/></label><div className="typed-signature">{name||"İmzan burada"}</div></TabsContent></Tabs><p className="conversion-note">Bu araç belgeye görsel imza ekler; sertifikalı elektronik imza oluşturmaz.</p><button className="primary" disabled={mode==="draw"?!drawn:!name.trim()} onClick={save}><Check size={17}/> İmzayı kullan</button></DialogContent></Dialog>
}
