const TEAMS = [
  // --- SÜPER LİG ---
  {
    id: "galatasaray",
    name: "Galatasaray",
    shortName: "GS",
    league: "Süper Lig",
    primaryColor: "#A90432",
    secondaryColor: "#FDB912",
    textColor: "#FFFFFF",
    badge: "🦁",
    gradient: "from-[#A90432] to-[#FDB912]"
  },
  {
    id: "fenerbahce",
    name: "Fenerbahçe",
    shortName: "FB",
    league: "Süper Lig",
    primaryColor: "#001A5E",
    secondaryColor: "#FFFF00",
    textColor: "#FFFFFF",
    badge: "🟡🔵",
    gradient: "from-[#001A5E] to-[#FFFF00]"
  },
  {
    id: "besiktas",
    name: "Beşiktaş",
    shortName: "BJK",
    league: "Süper Lig",
    primaryColor: "#111111",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🦅",
    gradient: "from-[#111111] to-[#444444]"
  },
  {
    id: "trabzonspor",
    name: "Trabzonspor",
    shortName: "TS",
    league: "Süper Lig",
    primaryColor: "#750B27",
    secondaryColor: "#17A2B8",
    textColor: "#FFFFFF",
    badge: "🌊",
    gradient: "from-[#750B27] to-[#17A2B8]"
  },
  {
    id: "basaksehir",
    name: "Başakşehir FK",
    shortName: "IBFK",
    league: "Süper Lig",
    primaryColor: "#EA5404",
    secondaryColor: "#152D64",
    textColor: "#FFFFFF",
    badge: "🦉",
    gradient: "from-[#EA5404] to-[#152D64]"
  },
  {
    id: "samsunspor",
    name: "Samsunspor",
    shortName: "SAM",
    league: "Süper Lig",
    primaryColor: "#D61F26",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🔴⚪",
    gradient: "from-[#D61F26] to-[#A00F15]"
  },
  {
    id: "eyupspor",
    name: "Eyüpspor",
    shortName: "EYP",
    league: "Süper Lig",
    primaryColor: "#800080",
    secondaryColor: "#FFD700",
    textColor: "#FFFFFF",
    badge: "💜💛",
    gradient: "from-[#800080] to-[#FFD700]"
  },
  {
    id: "goztepe",
    name: "Göztepe",
    shortName: "GÖZ",
    league: "Süper Lig",
    primaryColor: "#E30613",
    secondaryColor: "#FFED00",
    textColor: "#FFFFFF",
    badge: "🟡🔴",
    gradient: "from-[#E30613] to-[#FFED00]"
  },
  {
    id: "kasımpasa",
    name: "Kasımpaşa",
    shortName: "KAS",
    league: "Süper Lig",
    primaryColor: "#002B49",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "⚪🔵",
    gradient: "from-[#002B49] to-[#005596]"
  },
  {
    id: "sivasspor",
    name: "Sivasspor",
    shortName: "SİV",
    league: "Süper Lig",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🔴⚪",
    gradient: "from-[#E30613] to-[#990000]"
  },
  {
    id: "antalyaspor",
    name: "Antalyaspor",
    shortName: "ANT",
    league: "Süper Lig",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🦂",
    gradient: "from-[#E30613] to-[#C00]"
  },
  {
    id: "gaziantepfk",
    name: "Gaziantep FK",
    shortName: "GFK",
    league: "Süper Lig",
    primaryColor: "#E30613",
    secondaryColor: "#000000",
    textColor: "#FFFFFF",
    badge: "🦅",
    gradient: "from-[#E30613] to-[#000000]"
  },
  {
    id: "konyaspor",
    name: "Konyaspor",
    shortName: "KON",
    league: "Süper Lig",
    primaryColor: "#008037",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🦅",
    gradient: "from-[#008037] to-[#004d21]"
  },
  {
    id: "caykurrize",
    name: "Çaykur Rizespor",
    shortName: "RİZ",
    league: "Süper Lig",
    primaryColor: "#008037",
    secondaryColor: "#0033A0",
    textColor: "#FFFFFF",
    badge: "🟢🔵",
    gradient: "from-[#008037] to-[#0033A0]"
  },
  {
    id: "kayserispor",
    name: "Kayserispor",
    shortName: "KAY",
    league: "Süper Lig",
    primaryColor: "#FFD700",
    secondaryColor: "#E30613",
    textColor: "#111111",
    badge: "🟡🔴",
    gradient: "from-[#FFD700] to-[#E30613]"
  },
  {
    id: "bodrumfk",
    name: "Bodrum FK",
    shortName: "BOD",
    league: "Süper Lig",
    primaryColor: "#008037",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🟢⚪",
    gradient: "from-[#008037] to-[#004d21]"
  },
  {
    id: "alanyaspor",
    name: "Alanyaspor",
    shortName: "ALA",
    league: "Süper Lig",
    primaryColor: "#F58220",
    secondaryColor: "#008037",
    textColor: "#FFFFFF",
    badge: "🟠🟢",
    gradient: "from-[#F58220] to-[#008037]"
  },
  {
    id: "hatayspor",
    name: "Hatayspor",
    shortName: "HAT",
    league: "Süper Lig",
    primaryColor: "#750B27",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🍷⚪",
    gradient: "from-[#750B27] to-[#400010]"
  },
  {
    id: "adana_demir",
    name: "Adana Demirspor",
    shortName: "ADS",
    league: "Süper Lig",
    primaryColor: "#0033A0",
    secondaryColor: "#41B6E6",
    textColor: "#FFFFFF",
    badge: "⚡",
    gradient: "from-[#0033A0] to-[#41B6E6]"
  },

  // --- 1. LİG (PTT LİGİ) ---
  {
    id: "amedspor",
    name: "Amed SK",
    shortName: "AMD",
    league: "1. Lig",
    primaryColor: "#008037",
    secondaryColor: "#E30613",
    textColor: "#FFFFFF",
    badge: "🟢🔴",
    gradient: "from-[#008037] to-[#E30613]"
  },
  {
    id: "kocaelispor",
    name: "Kocaelispor",
    shortName: "KOC",
    league: "1. Lig",
    primaryColor: "#008037",
    secondaryColor: "#000000",
    textColor: "#FFFFFF",
    badge: "🟢⚫",
    gradient: "from-[#008037] to-[#000000]"
  },
  {
    id: "sakaryaspor",
    name: "Sakaryaspor",
    shortName: "SAK",
    league: "1. Lig",
    primaryColor: "#008037",
    secondaryColor: "#000000",
    textColor: "#FFFFFF",
    badge: "🟢⚫",
    gradient: "from-[#008037] to-[#111111]"
  },
  {
    id: "bursaspor",
    name: "Bursaspor",
    shortName: "BUR",
    league: "1. Lig",
    primaryColor: "#008037",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🐊",
    gradient: "from-[#008037] to-[#004d21]"
  },
  {
    id: "ankaragucu",
    name: "MKE Ankaragücü",
    shortName: "AGÜ",
    league: "1. Lig",
    primaryColor: "#001A5E",
    secondaryColor: "#FFD700",
    textColor: "#FFFFFF",
    badge: "🟡🔵",
    gradient: "from-[#001A5E] to-[#FFD700]"
  },
  {
    id: "genclebirligi",
    name: "Gençlerbirliği",
    shortName: "GB",
    league: "1. Lig",
    primaryColor: "#E30613",
    secondaryColor: "#000000",
    textColor: "#FFFFFF",
    badge: "🔴⚫",
    gradient: "from-[#E30613] to-[#000000]"
  },
  {
    id: "erzurumspor",
    name: "Erzurumspor FK",
    shortName: "ERZ",
    league: "1. Lig",
    primaryColor: "#0033A0",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🔵⚪",
    gradient: "from-[#0033A0] to-[#001A5E]"
  },
  {
    id: "corumfk",
    name: "Çorum FK",
    shortName: "ÇOR",
    league: "1. Lig",
    primaryColor: "#E30613",
    secondaryColor: "#000000",
    textColor: "#FFFFFF",
    badge: "🔴⚫",
    gradient: "from-[#E30613] to-[#000000]"
  },
  {
    id: "bandirmaspor",
    name: "Bandırmaspor",
    shortName: "BAN",
    league: "1. Lig",
    primaryColor: "#750B27",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🍷⚪",
    gradient: "from-[#750B27] to-[#400010]"
  },
  {
    id: "karagumruk",
    name: "Fatih Karagümrük",
    shortName: "FKG",
    league: "1. Lig",
    primaryColor: "#E30613",
    secondaryColor: "#000000",
    textColor: "#FFFFFF",
    badge: "🔴⚫",
    gradient: "from-[#E30613] to-[#000000]"
  },
  {
    id: "istanbulspor",
    name: "İstanbulspor",
    shortName: "İST",
    league: "1. Lig",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
    textColor: "#FFFFFF",
    badge: "🟡⚫",
    gradient: "from-[#FFD700] to-[#000000]"
  },
  {
    id: "sanliurfaspor",
    name: "Şanlıurfaspor",
    shortName: "URF",
    league: "1. Lig",
    primaryColor: "#FFED00",
    secondaryColor: "#008037",
    textColor: "#111111",
    badge: "🟡🟢",
    gradient: "from-[#FFED00] to-[#008037]"
  },
  {
    id: "adanaspor",
    name: "Adanaspor",
    shortName: "ADA",
    league: "1. Lig",
    primaryColor: "#F58220",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🟠⚪",
    gradient: "from-[#F58220] to-[#CC5500]"
  },
  {
    id: "boluspor",
    name: "Boluspor",
    shortName: "BOL",
    league: "1. Lig",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🔴⚪",
    gradient: "from-[#E30613] to-[#990000]"
  },
  {
    id: "umraniyespor",
    name: "Ümraniyespor",
    shortName: "ÜMR",
    league: "1. Lig",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🔴⚪",
    gradient: "from-[#E30613] to-[#A00F15]"
  },
  {
    id: "manisafk",
    name: "Manisa FK",
    shortName: "MAN",
    league: "1. Lig",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "⚫⚪",
    gradient: "from-[#000000] to-[#333333]"
  },
  {
    id: "pendikspor",
    name: "Pendikspor",
    shortName: "PEN",
    league: "1. Lig",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🔴⚪",
    gradient: "from-[#E30613] to-[#990000]"
  },
  {
    id: "igdirfk",
    name: "Iğdır FK",
    shortName: "IĞD",
    league: "1. Lig",
    primaryColor: "#008037",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🟢⚪",
    gradient: "from-[#008037] to-[#005520]"
  },
  {
    id: "esenler_erok",
    name: "Esenler Erokspor",
    shortName: "ERK",
    league: "1. Lig",
    primaryColor: "#008037",
    secondaryColor: "#FFED00",
    textColor: "#FFFFFF",
    badge: "🟢🟡",
    gradient: "from-[#008037] to-[#FFED00]"
  },
  {
    id: "keciorengucu",
    name: "Keçiörengücü",
    shortName: "KÖG",
    league: "1. Lig",
    primaryColor: "#750B27",
    secondaryColor: "#FFFFFF",
    textColor: "#FFFFFF",
    badge: "🍷⚪",
    gradient: "from-[#750B27] to-[#400010]"
  },
  {
    id: "yenimalatya",
    name: "Yeni Malatyaspor",
    shortName: "YMS",
    league: "1. Lig",
    primaryColor: "#FFED00",
    secondaryColor: "#000000",
    textColor: "#111111",
    badge: "🟡⚫",
    gradient: "from-[#FFED00] to-[#000000]"
  }
];

module.exports = { TEAMS };
